puts "this is stash brach"
puts "this is stash brach"
puts "this is stash brach"
puts "this is stash brach"
puts "this is stash brach"
puts "this is stash brach"
puts "this is stash brach"
puts "this is stash brach"

puts "now new"